/**
 * Ed25519 keypair and signing helpers for the OPPF mock server.
 *
 * A 32-byte seed is generated at build time, the corresponding public key is baked into the
 * Electron build as a trusted signing key, and the mock server uses the seed to sign each OPPF body
 * it serves.
 *
 * - {@link TEST_OPPF_SEED_PATH}: The base64-encoded 32-byte Ed25519 seed (no trailing newline).
 * - {@link TEST_OPPF_PUBLIC_KEY_PATH}: The base64-encoded 32-byte public key (no trailing newline).
 *
 * Both files are regenerated by `apps/desktop/tools/build-electron.mjs` on each build (testing mode
 * only) and are saved to `apps/desktop/.temp/playwright/`.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

import tweetnacl from 'tweetnacl';

/** Absolute path to the `apps/desktop` directory. */
const APP_DIR = path.resolve(import.meta.dirname, '..', '..', '..', '..', '..');

/** Temporary directory holding the ephemeral OPPF signing keys. */
export const TEST_KEY_DIR = path.join(APP_DIR, '.temp', 'playwright');

/** File holding the base64-encoded 32-byte Ed25519 seed. */
export const TEST_OPPF_SEED_PATH = path.join(TEST_KEY_DIR, 'oppf-signature-key');

/** File holding the base64-encoded 32-byte Ed25519 public key. */
export const TEST_OPPF_PUBLIC_KEY_PATH = path.join(TEST_KEY_DIR, 'oppf-signature-key.pub');

export interface Ed25519Keypair {
    /** 32-byte Ed25519 public key. */
    readonly publicKey: Uint8Array;
    /** 64-byte expanded Ed25519 secret key (seed ++ public key, `tweetnacl` convention). */
    readonly secretKey: Uint8Array;
}

/**
 * Derive an Ed25519 keypair from a 32-byte seed.
 *
 * @throws If `seed` is not exactly 32 bytes.
 */
export function keypairFromSeed(seed: Uint8Array): Ed25519Keypair {
    if (seed.byteLength !== 32) {
        throw new Error(`Ed25519 seed must be exactly 32 bytes, got ${seed.byteLength}`);
    }
    const {publicKey, secretKey} = tweetnacl.sign.keyPair.fromSeed(seed);
    return {publicKey, secretKey};
}

/** Generate a fresh random Ed25519 keypair. */
export function generateKeypair(): Ed25519Keypair {
    const {publicKey, secretKey} = tweetnacl.sign.keyPair();
    return {publicKey, secretKey};
}

/**
 * Load the persisted test OPPF keypair (seed produced by `apps/desktop/tools/build-electron.mjs`).
 *
 * The corresponding public key is baked into the Electron build as a trusted signing key, so the
 * seed must remain stable across the build and the mock server lifetime.
 *
 * @throws If the seed file is missing or contains an invalid 32-byte base64 string.
 */
export function loadTrustedTestKeypair(): Ed25519Keypair {
    let seedBase64: string;
    try {
        seedBase64 = fs.readFileSync(TEST_OPPF_SEED_PATH, {encoding: 'utf8'}).trim();
    } catch (error) {
        throw new Error(
            `OPPF test signing key not found at ${TEST_OPPF_SEED_PATH}. Build the app (with \`TURBO_BUILD_MODE=testing\`) before starting the mock server. Error: ${error}`,
        );
    }
    return keypairFromSeed(Buffer.from(seedBase64, 'base64'));
}

/**
 * Sign the given OPPF body bytes with `secretKey` and return the 88-character base64-encoded
 * Ed25519 signature. Matches the `oppf-tool sign` Rust command.
 */
export function signOppfBody(body: Uint8Array, secretKey: Uint8Array): string {
    return Buffer.from(tweetnacl.sign.detached(body, secretKey)).toString('base64');
}
